name: Checks
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - run: pip install --upgrade pip
    - run: pip install black==21.6b0 mypy==v0.931 poetry
    - run: poetry install
    - run: black --diff --check $(git ls-files '*.py')
    - run: poetry run mypy --strict $(git ls-files '*.py')
